#!/bin/bash

find_files() {
  for file in "$1"/*; do
    if [[ -f "$file" && "$file" == *.gif ]]; then
      echo "$(basename "${file%.*}")"
    elif [[ -d "$file" ]]; then
      find_files "$file"
    fi
  done
}

find_files "." | LC_COLLATE=C sort -f
echo

